export const image = [
    {
      "ID": "BasicTechnicalWriting",
      "ImageUrl": "https://cdn.pixabay.com/photo/2014/02/08/04/55/maldives-261506_960_720.jpg",
      "Name": "Tourism in the Maldives",
      "ShortDesc": "Nevertheless, the Maldives have frequently come under criticism for their lack of protection of the local shark populations, which have sharply decreased after being hunted extensively for decades. In some areas, sharks have entirely disappeared. Sharks are hunted primarily for their fins. Shark fins are exported from the Maldives to other countries in Asia, where they are regarded as a delicacy. The fins are amputated from the live animals, which are then thrown back alive into the sea.Although this practice is prohibited by law in the Maldives, these laws are not respected or enforced by the local authorities.The country's coral reefs, which protect it from storm surges and serve as the main attraction for the tourism-driven economy, are in danger of being damaged or destroyed by poorly handled waste disposal methods.The level of crime in the Maldives is low, but some personal belongings left on the beaches or in the hotels can be stolen. Knife crime in populated areas, like the capital Male, has increased. Tourists should also follow local advice on if there is any danger with swimming."
    },
    {
      "ID": "ConfluenceAdvanced",
      "ImageUrl": "https://cdn.pixabay.com/photo/2017/12/15/13/51/polynesia-3021072__340.jpg",
      "Name": "Travel to Iceland",
      "ShortDesc": "Today's cruise ships are large ships that serve as floating hotels for vacationers. Cruise ships include restaurants, shops, swimming pools, theaters, and cinemas. Some cruise ships even offer college-level courses onboard.The founders wanted to create a central marketplace for tourism in Iceland, where travelers could find reliable travel information and book directly from local suppliers.In January 2017, the City of Reykjavík chose Guide to Iceland as its Official Tourist Information Partner. The award coincided with the relocation of Reykjavik's main Tourist Information Center to Reykjavík City Hall, where it was operated by Guide to Iceland.In 2018 the U.S.-based General Electrics Pension Trust invested in Guide to Iceland through State Street Global Advisors, becoming the second-largest shareholder of the company.Guide to Iceland curates and quality checks Icelandic service providers and acts as a guarantee to travelers that they receive the services they book.It provides information and customer service in fourteen languages and its website contains numerous travel articles about Iceland.Guide to Iceland was chosen as the Best Exponential Startup at the 2016 Nordic Startup Awards."
    },
    {
      "ID": "ConfluenceBasic",
      "ImageUrl": "https://cdn.pixabay.com/photo/2018/07/16/16/08/island-3542290_960_720.jpg",
      "Name": "Cruising the oceans",
      "ShortDesc": "Human interest in the sea fuels a multi-billion dollar a year ocean tourism industry. Ocean tourism refers to pleasure travel in which the sea is the primary focus of activities. Ocean tourism comes in many forms including cruises, ecotourism, and fishing expeditions.Cruises are one of the most popular forms of ocean tourism. In the late nineteenth and early twentieth century, cruise liners were needed to carry passengers across the oceans. Many of these cruise ships—including the ill-fated Titanic, which sank in 1912 killing over 1,500 people.They began to change the concept of the cruise itself to a vacation. Ships started traveling to exotic locations and offering more services and activities.Tourism on the oceans provides a major boost to the economies of countries that are popular cruise destinations. In the United States, nearly 8 million people take a cruise every year. Cruises contribute an estimated $18 billion per year to the American economy. Cruise lines directly employee over 25,000 Americans. An estimated 250,000 American jobs are supported by the cruise industry."
    },
    {
      "ID": "XMLAuthor",
      "ImageUrl": "https://cdn.pixabay.com/photo/2018/10/19/12/14/train-3758523_960_720.jpg",
      "Name": "Tourism in Paris",
      "ShortDesc": "He entered a competition for students studying at the university. The winning proposal would stand as the centerpiece of the 1889 Exposition. Eiffel's was one of over 100 submissions. Eiffel's proposal was finally chosen in June 1886. Even before its construction, the Tower's uniqueness was noticed. The Eiffel Tower was finally inaugurated on March 31, 1889.[5] Currently, about 6.9 million people visit the Eiffel Tower each year.Museums re-opened in 2021, with limitations on the number of visitors at a time and a requirement that visitors wear masks.The Eiffel Tower is acknowledged as the universal symbol of both Paris and France. It was originally designed by Émile Nouguier and Maurice Koechlin. In March 1885, Gustave Eiffel, known primarily as a successful iron engineer, submitted a plan for a tower to the French Ministre du Commerce et de l'IndustrieTourism in Paris is a major income source. Paris received 12.6 million visitors in 2020, measured by hotel stays, a drop of 73 percent from 2019, due to the COVID-19 pandemic. The number of foreign visitors declined by 80.7 percent."
    },
    {
      "ID": "AdvancedTechnicalWriting-API",
      "ImageUrl": "https://cdn.pixabay.com/photo/2017/03/05/00/34/panorama-2117310_960_720.jpg",
      "Name": "Miami city USA",
      "ShortDesc": "Take a number of diverse cultures, add a strong dose of the arts and a splash of ocean water, and you have Miami. Looking at the fantastic art museums and the blossoming gastronomical scene, you might find it hard to believe that just a century ago, this colorful Floridian city was covered in swampland. Once developers rushed into the area, one of the most popular tourist destinations and spectacular city skylines in the country was born. Today, with South Beach before you and the Everglades behind you, you can walk through the bustling streets past historical homes with Spanish words and Caribbean music floating into your ears.Its reputation for vibrant nightlife and extravagant parties is realized in Miami Beach, a barrier island to the east of the mainland. Meanwhile, the down-to-earth city proper cultivates an artsy vibe. For a taste of Miami Beach, sign up for one of the city's best boat tours, where you'll be able to marvel at the glitzy skyline from the water on a boat tour or via parasail."
    
    },
    {
      "ID": "BasicDITA-XML",
      "ImageUrl": "https://cdn.pixabay.com/photo/2016/07/30/00/03/winding-road-1556177_960_720.jpg",
      "Name": "Manali to Ladakh across the Himalaya",
      "ShortDesc": "You could follow the mountain circuit from Shimla to Ladakh and on to Kashmir by rented jeep but we strongly recommend traveling by rented Enfield Bullet motorcycle for the life-affirming drama of pulling over by the roadside to find yourself utterly alone in these high-altitude deserts in the rain shadow of the Himalayas.As you enter Jodhpur, you’ll immediately spot the lapis-colored buildings that earned the Blue City its name – the homes of brahmins, priests in the Hindu caste system. Get another blast of Rajput military might at Mehrangarh Fort, then drive west through serious desert country to the sand-yellow city of Jaisalmer, whose fortified walls look almost carved from the desert itself. Close off the loop via Bikaner, where you’ll leave the tourist crowds behind before diving back into the thick of things in Jaipur. There’s little vegetation and even less shade, and the cold and altitude will hit you like a sledgehammer. Recuperate with trips to Buddhist monasteries and yoga classes in Leh, then hit the road again for a very different take on the Himalayas in Kashmir. but as the hills turn from dust-yellow to lush green, the culture shifts from Buddhism to Islam as the minarets of Srinagar loom into view. The Kashmir valley is sometimes troubled, but when it’s calm, the experience of watching Dal Lake appearing slowly through the morning mist from the deck of a houseboat is simply sublime. "
    },
    {
      "ID": "AdvancedDITA-XML",
      "ImageUrl": "https://cdn.pixabay.com/photo/2017/10/28/07/47/woman-2896389_960_720.jpg",
      "Name": "Norway is a Scandinavian Country ",
      "ShortDesc": "We Norwegians tend to believe that Norway is the center of the earth and everyone knows who we are. The truth is that Norway isn't as large as we want to believe and everyone doesn't even know that Norway even is a country.Svalbard, however, is a Norwegian archipelago between mainland Norway and the North Pole where there are more Polar Bears than people. Still, it's rare that there are any incidents between the inhabitants and Polar Bears.The currency we use in Norway is the Norwegian Krone. So, if you're traveling with only Euro you won't come far. The Norwegian Krone was recently weakened which means that if you're traveling to Norway in the near future it will be cheaper than what it was only one year ago. It should be mentioned that Norway is using less and less cash. You can mostly anything with a credit card, even taxis and hot dogs! That means that it's not a crisis if you forgot to bring cash.Norway is known to be one of the safest countries in the world. Crime rates are extremely low even in major cities such as Oslo, Bergen, Trondheim, and Stavanger.Another thing to keep in mind is that the weather changes a lot between seasons. Make sure that you always bring enough clothes when traveling to Norway as it does get cold! Keeping an eye on the weather forecast is always a good idea.  "
    },
    {
      "ID": "xMetaLAuthor",
      "ImageUrl": "https://cdn.pixabay.com/photo/2015/01/28/23/10/mosque-615415_960_720.jpg",
      "Name": "Mosque Abu Dhabi Architecture",
      "ShortDesc": "It’s easy to stay in our circles, to keep to the people we know, who are familiar, who look and believe like we do. But there’s power in widening our perspective, in seeking out those who are different from us.Christianity and Islam are the two largest religions in the world, and they’re often set up in opposition to each other. So what if you took a step and visited a mosque. What new relationships, connections, and understanding could be borne out of your visit?Mosques are places of worship for Muslims, but also contain teaching and community spaces. They’re a central gathering place for Muslims, both for worship and faith and also for community and learning.Muslims pray five times a day facing Mecca. The mosque is available for any and all of these prayer times, but communal praying at the mosque is always encouraged, particularly for the midday prayer, and especially for midday prayers on Friday.Some mosques hold periodic interfaith gatherings or open houses, so you can look to see if one of these will be happening at your local mosque.Many mosques understandably have heightened security. And in some cases, like after the New Zealand mass shooting, they might be asking visitors to schedule a visit for a later date. "
    },
    {
      "ID": "MadCapFlare",
      "ImageUrl": "https://cdn.pixabay.com/photo/2021/01/27/13/47/cliff-5954980_960_720.jpg",
      "Name": "Beautiful place of Bali in Thailand",
      "ShortDesc": "Bali is a true traveler’s paradise where you’ll never run out of things to see and do. The only challenge is figuring out which attractions and activities to make time for! To help you see the very best of the island, here is the ultimate.There are many different options for getting around Bali. Courageous travelers may choose to rent a car or a moped but, if you prefer a more relaxing experience, then hiring a professional driver to take you between destinations is the way to go. Bali‘s professional drivers are familiar with the roads and traffic and will get you from point A to point B quickly and securely. Hiring a private driver for a day will cost around 400,000 IDR. If you just need to get from attraction to attraction around town, then the best options are either a taxi or one of the two local ride-hailing apps: Grab and Gojek. If you opt for a taxi, then Blue Bird Taxi is the most highly recommended option as it charges by the meter.Upon arriving in Bali, you should naturally head to the beach, so the first stop on this itinerary is the resort area of Nusa Dua. Located in southern Bali, Nusa Dua is just a 20-minute drive from Ngurah Rai International Airport.  "
    }
  ]